server:
  port: 7013
  servlet:
    context-path: /book-mgmt
spring:
  application:
     name: book-mgmt
  datasource:
     url: jdbc:mysql://localhost:3306/book_exchange_db?createDatabaseIfNotExist=true
     username: sagari
     password: sagari
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

eureka:
   client:
     service-url:
       defaultZone: http://localhost:8761/service-discovery/eureka
API_GATEWAY: http://localhost:9090/book-mgmt
        
        
 
     
