server:
  port: 9676
  servlet:
    context-path: /user-mgmt
spring:
  application:
     name: user-mgmt
  datasource:
     url: jdbc:mysql://localhost:3306/book_exchange_db?createDatabaseIfNotExist=true
     username: sagari
     password: sagari
     driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
book:
  jwtSecret: WZT7di2p46QeOL3rgkUzA4B9o9Oc0eZpZMVybqFIguneOoT6fJa82Jzttdn1LTpPmtjcNZFlTvw52YoBiQ
  jwtExpiration: 3000000
  
eureka:
   client:
     service-url:
       defaultZone: http://localhost:8761/service-discovery/eureka
API_GATEWAY: http://localhost:9090/user-mgmt
        
        
 
     
