server:
  port: 8761
  servlet:
    context-path: /service-discovery
spring:
  application:
    name: service-discovery
management:
    endpoints:
        web:
            exposure:
                include: "*"
            discovery:
                enabled: true
    endpoint:
        health:
          show-details: always
API_GATEWAY: http://localhost:9090/service-discovery
eureka:
    server:
        context-path: /service-discovery
    client:
        service-url:
            defaultZone: http://localhost:8761/service-discovery/eureka
